# Generated by Django 3.1.8 on 2021-06-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='key',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
